from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Realm)
admin.site.register(Page)
admin.site.register(PlotArc)
admin.site.register(PlotPoint)
admin.site.register(Character)
admin.site.register(Setting)
admin.site.register(Item)
admin.site.register(Magic)
admin.site.register(SocialStructure)
admin.site.register(CharacterRelationship)
admin.site.register(ContentBlock)
admin.site.register(TextBlock)
admin.site.register(ImageBlock)
admin.site.register(AliasBlock)
admin.site.register(QualityBlock)
admin.site.register(QualityType)
admin.site.register(CharacterBlock)
admin.site.register(ItemBlock)
admin.site.register(CharacterListBlock)
admin.site.register(GoalBlock)
admin.site.register(GraphBlock)
admin.site.register(CharacterWebBlock)
admin.site.register(TimelineBlock)
admin.site.register(MapBlock)
admin.site.register(Pin)
admin.site.register(Region)
admin.site.register(RegionType)