# Generated by Django 4.1.7 on 2023-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("media_project_image", models.ImageField(upload_to="images/")),
                ("publish_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("header_image", models.ImageField(upload_to="images/")),
                ("subheading", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("text", models.TextField()),
            ],
        ),
    ]
