# Generated by Django 4.1.3 on 2023-01-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipage",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="wikipage",
            name="object_id",
        ),
        migrations.AddField(
            model_name="wikipage",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
            preserve_default=False,
        ),
    ]
