import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';

import axios from 'axios';
import { useEffect, useState } from 'react';

import styles from '@/styles/Home.module.css';


const inter = Inter({ subsets: ['latin'] });



function Realms ()
{
  const [realms, setRealms] = useState([]);

  useEffect(() =>
  {
    axios.get('http://127.0.0.1:8000/api/realms/')
      .then(response =>
      {
        setRealms(response.data['realms']);
      })
      .catch(error => console.error(error));
  }, []);

  return (
    <>
      <Head>
        <title>Realms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ styles.main }>

        <div className={ styles.center }>
          <h1 className={ styles.title }>
            Realms
          </h1>
        </div>

        <div className={ styles.center }>
          { realms.length > 0 && (
            <>
              <ul>
                { realms.map((realm) => (
                  <li key={ realm.id }>{ realm.name }<br />{ realm.description }</li>
                )) }
              </ul>
              <div></div>
            </>
          ) }
        </div>

      </main>
    </>
  );
}

export default Realms;
