import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';

import axios from 'axios';
import { useEffect, useState } from 'react';

import styles from '@/styles/Home.module.css';


// @
// *
// ?
// !
// TODO:
// FIXME:
// [x]

function Settings ()
{
     const [settings, setSettings] = useState([]);

     useEffect(() =>
     {
          axios.get('http://127.0.0.1:8000/api/settings/')
               .then(response =>
               {
                    console.log(response.data['pages']);
                    setSettings(response.data['pages']);
               })
               .catch(error => console.error(error));
     }, []);

     return (
          <>
               <Head>
                    <title>Settings</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <main className={ styles.main }>

                    <div className={ styles.center }>
                         <h1 className={ styles.title }>
                              Settings
                         </h1>
                    </div>

                    <div className={ styles.center }>
                         { settings.length > 0 && (
                              <>
                                   <ul>
                                        { settings.map((setting) => (
                                             <li key={ setting.id }>{ setting.name }<img style={ { 'width': '500px' } } src={ 'http://127.0.0.1:8000/media/' + setting.header_image } /><br />{ setting.description }</li>
                                        )) }
                                   </ul>
                                   <div></div>
                              </>
                         ) }
                    </div>

               </main>
               <div className="icon-box" style={ { "width": "18rem;" } }>
                    <img src="..." className="card-img-top" alt="..." />
                    <div className="card-body">
                         <h5 className="card-title">Card title</h5>
                         <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                         <a href="#" className="btn btn-primary">Go somewhere</a>
                    </div>
               </div>
          </>
     );
}

export default Settings;
