# Generated by Django 4.1.7 on 2023-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "primary_content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_first_published", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("primary_color", models.CharField(default="#fff", max_length=7)),
                ("secondary_color", models.CharField(default="#fff", max_length=7)),
                ("tertiary_color", models.CharField(default="#fff", max_length=7)),
                (
                    "button_style",
                    models.CharField(default="#btn btn-primary", max_length=10),
                ),
                ("corner_roundness", models.PositiveSmallIntegerField(default=0)),
                ("background_blur_amount", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserMediaProjectAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPageAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRealmsAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
