# Generated by Django 4.1.7 on 2023-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField()),
                ("primary_content_type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("date_first_published", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("primary_color", models.CharField(max_length=7)),
                ("secondary_color", models.CharField(max_length=7)),
                ("tertiary_color", models.CharField(max_length=7)),
                ("button_style", models.CharField(max_length=10)),
                ("corner_roundness", models.PositiveSmallIntegerField()),
                ("background_blur_amount", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserMediaProjectAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPageAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRealmsAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[("O", "Owner"), ("E", "Editor"), ("V", "Viewer")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
