# Generated by Django 4.1.7 on 2023-02-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldbuilding", "0002_alter_characterlistblock_characters_and_more"),
        ("wiki", "0002_initial"),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="media_projects",
            field=models.ManyToManyField(to="wiki.mediaproject"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="realms",
            field=models.ManyToManyField(
                through="main.UserRealmsAccess", to="worldbuilding.realm"
            ),
        ),
    ]
