# Generated by Django 4.1.3 on 2023-01-07 05:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wiki", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("strength", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("header_image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="RegionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_type_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
                ("overall_development", models.SmallIntegerField()),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x_label", models.CharField(max_length=100)),
                ("y_label", models.CharField(max_length=100)),
                ("data", models.JSONField()),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="ImageBlock",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="Magic",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="MapBlock",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="PlotArc",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
                (
                    "media_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wiki.mediaproject",
                    ),
                ),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="PlotPoint",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
                ("plot_progression", models.SmallIntegerField()),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="SocialStructure",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField()),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="Realm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="realm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="worldbuilding.realm"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="worldbuilding.page"
            ),
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("plot_points", models.ManyToManyField(to="worldbuilding.plotpoint")),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.page",
                    ),
                ),
                (
                    "encompassing_setting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worldbuilding.setting",
                    ),
                ),
            ],
            bases=("worldbuilding.page",),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "region_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldbuilding.regiontype",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldbuilding.mapblock",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="backdrop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backdrop",
                to="worldbuilding.setting",
            ),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="characters",
            field=models.ManyToManyField(
                related_name="characters", to="worldbuilding.character"
            ),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="items",
            field=models.ManyToManyField(related_name="items", to="worldbuilding.item"),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="magic_systems",
            field=models.ManyToManyField(
                related_name="magic_systems", to="worldbuilding.magic"
            ),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="pages",
            field=models.ManyToManyField(related_name="pages", to="worldbuilding.page"),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="plot_arc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="worldbuilding.plotarc",
            ),
        ),
        migrations.AddField(
            model_name="plotpoint",
            name="social_structures",
            field=models.ManyToManyField(
                related_name="social_structures", to="worldbuilding.socialstructure"
            ),
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("icon", models.ImageField(upload_to="images/")),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldbuilding.mapblock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemBlock",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldbuilding.item",
                    ),
                ),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="CharacterWeb",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "relationships",
                    models.ManyToManyField(to="worldbuilding.characterrelationship"),
                ),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="character1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character1",
                to="worldbuilding.character",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="character2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character2",
                to="worldbuilding.character",
            ),
        ),
        migrations.CreateModel(
            name="CharacterList",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("characters", models.ManyToManyField(to="worldbuilding.character")),
            ],
            bases=("worldbuilding.contentblock",),
        ),
        migrations.CreateModel(
            name="CharacterBlock",
            fields=[
                (
                    "contentblock_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldbuilding.contentblock",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldbuilding.character",
                    ),
                ),
            ],
            bases=("worldbuilding.contentblock",),
        ),
    ]
