# Generated by Django 4.1.7 on 2023-02-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldbuilding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterlistblock",
            name="characters",
            field=models.ManyToManyField(
                related_name="characters_in_character_list",
                to="worldbuilding.character",
            ),
        ),
        migrations.AlterField(
            model_name="characterwebblock",
            name="relationships",
            field=models.ManyToManyField(
                related_name="relationships", to="worldbuilding.characterrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="plotpoint",
            name="characters",
            field=models.ManyToManyField(
                related_name="characters", to="worldbuilding.character"
            ),
        ),
        migrations.AlterField(
            model_name="plotpoint",
            name="items",
            field=models.ManyToManyField(related_name="items", to="worldbuilding.item"),
        ),
        migrations.AlterField(
            model_name="plotpoint",
            name="magic_systems",
            field=models.ManyToManyField(
                related_name="magic_systems", to="worldbuilding.magic"
            ),
        ),
        migrations.AlterField(
            model_name="plotpoint",
            name="pages",
            field=models.ManyToManyField(related_name="pages", to="worldbuilding.page"),
        ),
        migrations.AlterField(
            model_name="plotpoint",
            name="social_structures",
            field=models.ManyToManyField(
                related_name="social_structures", to="worldbuilding.socialstructure"
            ),
        ),
        migrations.AlterField(
            model_name="timelineblock",
            name="plot_points",
            field=models.ManyToManyField(
                related_name="plot_points", to="worldbuilding.plotpoint"
            ),
        ),
    ]
